### ISSUE TITLE
Duplicate DataSources

### ISSUE THREAD

**Issue by T4E-JAnderson** [Tools4everBV/HelloID-Conn-SA-Source-HelloID-DelegatedForms#1]
If different elements on a Form use the same Source, it results in the script attempting to create the target DataSource multiple times.  Example:
Powershell data source 'DPWR AD OUs' created: 4d732f50-6280-42d4-9b8c-e875806e46
70
Powershell data source 'DPWR AD Groups' created: da1b1a70-2eb7-4a53-b4bc-848cfc7
70afd
Powershell data source 'DPWR AD Groups' already exists: da1b1a70-2eb7-4a53-b4bc-
848cfc770afd
Powershell data source 'DPWR Get Config' created: 5c3d9878-ed6a-469a-9931-2dc7de
043cf7
Powershell data source 'DPWR AD Groups' already exists: da1b1a70-2eb7-4a53-b4bc-
848cfc770afd
Powershell data source 'DPWR AD OUs' already exists: 4d732f50-6280-42d4-9b8c-e87
5806e4670

**Comment by Michiel85** [comment]
That is correct. The script outcome is still working, but can be optimized. For now it is "as designed"
