### ISSUE TITLE
Misspelling for Write-Warning

### ISSUE THREAD

**Issue by msheldont4e** [Tools4everBV/HelloID-Conn-SA-Source-HelloID-DelegatedForms#3]
https://github.com/Tools4everBV/HelloID-Conn-SA-Source-HelloID-DelegatedForms/blob/487e9f1a205357b56cb9d777d551eabdf761e1fc/generate-all-in-one.ps1#L667

**Comment by Michiel85** [comment]
Thnx! fixed the typo
